# Generated by Django 3.2.6 on 2021-08-10 03:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_alter_usuarios_data_de_cadastro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservas',
            name='id',
            field=models.UUIDField(auto_created=True, default=uuid.uuid4, help_text='uniqueid', primary_key=True, serialize=False),
        ),
    ]
