# Generated by Django 3.2.5 on 2021-08-12 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_alter_reservas_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='agenda.usuarios'),
        ),
    ]
