# Generated by Django 3.2.5 on 2021-08-13 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0006_alter_limpeza_horarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limpeza',
            name='horarios',
            field=models.TimeField(),
        ),
    ]
