# Generated by Django 3.2.5 on 2021-09-28 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ginasios',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=30)),
                ('tipo', models.CharField(max_length=30)),
                ('estagio_de_evolucao', models.IntegerField()),
                ('elemento', models.CharField(max_length=10)),
                ('descricao', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Treinador',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=30)),
                ('insignias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemons.ginasios')),
                ('pokemons_coletados', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemons.pokemon')),
            ],
        ),
        migrations.CreateModel(
            name='Territorios',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=20)),
                ('descricao', models.CharField(max_length=200)),
                ('pokemons', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemons.pokemon')),
            ],
        ),
        migrations.AddField(
            model_name='ginasios',
            name='localizacao',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pokemons.territorios'),
        ),
    ]
