# Generated by Django 3.2.5 on 2021-09-28 17:46

from django.db import migrations, models
import pokemons.models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to=pokemons.models.upload_de_pokemon),
        ),
        migrations.AddField(
            model_name='territorios',
            name='imagemTerritorial',
            field=models.ImageField(blank=True, null=True, upload_to=pokemons.models.upload_de_pokemon),
        ),
        migrations.AddField(
            model_name='treinador',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=pokemons.models.upload_de_pokemon),
        ),
    ]
