# Generated by Django 3.2.5 on 2021-10-06 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treinador',
            name='insignias',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='pokemons.ginasios'),
        ),
        migrations.AlterField(
            model_name='treinador',
            name='pokemons_coletados',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='pokemons.pokemon'),
        ),
    ]
